export const GET_TODO = {
    SUCCESS: "GET_TODO_SUCCESS",
    PENDING: "GET_TODO_PENDING",
    FAILURE: "GET_TODO_FAILURE"
}
export const FETCH_TODO = {
    SUCCESS : "FETCH_TODO_SUCCESS",
    PENDING : "FETCH_TODO_PENDING",
    FAILURE : "FETCH_TODO_FAILURE",
}
